# Site settings
title: Toby Hede
description: Toby Hede
url: https://tobyhede.com

# User settings
email: toby@tobyhede.com
social:
  - label: twitter
    url: https://twitter.com/tobyhede
  - label: linkedin
    url: https://au.linkedin.com/in/tobyhede
  - label: github
    url: https://github.com/tobyhede
  - label: reddit
    url: https://www.reddit.com/r/ServerlessPatterns/

sass:
  sass_dir: _sass
  style: compressed

# Google-analytics
google-analytics:
  id: "UA-75017126-2"