[book]
authors = ["Toby Hede"]
language = "en"
multilingual = false
src = "src"
title = "///////////////////"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
smart-punctuation = true
mathjax-support = false
# additional-css = ["custom.css", "custom2.css"]
# additional-js = ["custom.js"]
git-repository-url = "https://github.com/tobyhede/tobyhede.com"
git-repository-icon = "fa-github"
cname = "tobyhede.com"
input-404 = "404-not-found.md"

[output.html.print]
enable = true     # include support for printable output
page-break = true # insert page-break after each chapter

[output.html.search]
enable = false
